In [7]:
import numpy as np

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
z = np.ones(5)
print(z)
type(z)
z.shape
type(z[3])

[1. 1. 1. 1. 1.]


numpy.float64

In [13]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
np.arange(3,56)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55])

In [15]:
o2 = 2*np.ones(10)
print(o2)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [22]:
np.arange(10,51,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [23]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
3*np.ones(21)


array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3.])

In [10]:
a = np.random.rand(7,3)

In [9]:
a + 1 


array([[1.79321159, 1.73191336, 1.9728791 ],
       [1.77067204, 1.31529682, 1.57243408],
       [1.23633893, 1.96824585, 1.70008316],
       [1.36792945, 1.79361161, 1.15877092],
       [1.1894366 , 1.38078649, 1.83398802],
       [1.32586509, 1.7872318 , 1.72038328],
       [1.70358159, 1.70181115, 1.08558966]])

In [10]:
np.random.randint(1,56)

24

In [12]:
  a.sum()

12.110060575374781

In [13]:
a.std()

0.2707097336323577

In [14]:
a.round()

array([[1., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 1.],
       [1., 1., 0.]])

In [16]:
o2.sum()

20.0

In [18]:
a.sum() + o2.sum()

32.11006057537478

In [19]:
a.sum(axis=0)

array([3.38703528, 4.67889708, 4.04412822])

In [24]:
s= a.sum(axis=1,keepdims=True)

In [25]:
s.shape

(7, 1)

In [26]:
 s+a

array([[3.29121563, 3.2299174 , 3.47088315],
       [2.42907498, 1.97369976, 2.23083702],
       [2.14100687, 2.87291379, 2.6047511 ],
       [1.68824143, 2.11392359, 1.4790829 ],
       [1.5936477 , 1.78499759, 2.23819912],
       [2.15934526, 2.62071197, 2.55386345],
       [2.19456399, 2.19279355, 1.57657206]])

In [2]:
import pandas as pd


In [12]:
f = pd.DataFrame(a,index=' A B C D E F G'.split(), columns = '1 2 3 '.split())
f

1         2         3
A  0.576041  0.608850  0.908087
B  0.392840  0.137814  0.232168
C  0.490446  0.795385  0.852140
D  0.614101  0.844688  0.710568
E  0.975580  0.550267  0.384747
F  0.168528  0.329071  0.506355
G  0.024468  0.403029  0.414146