In [3]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [4]:
titanic =pd.read_csv('final_dataset.csv')
dataset=titanic.copy()
X=np.asarray(dataset.drop('Survived',1))
y=np.asarray(dataset['Survived'])

In [5]:


#splliting data for training and testing
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 0)

In [6]:
#normalizing the data by keeping them in standard scale
sc= StandardScaler()
X_train_normalized = sc.fit_transform(X_train)
X_test_normalized = sc.transform(X_test)

In [7]:
#defining the neural network architechture

numDims = X_train_normalized.shape[1] #gets the number of features of the data
#fully conected architecture hence use dense
dnnModel = tf.keras.Sequential([
    layers.Dense(15,activation='elu',input_shape =(numDims,)),
    
    layers.Dropout(0.3),
    layers.Dense(19,activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.21),
    layers.Dense(120,activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),
    layers.Dense(160,activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),
    layers.Dense(20,activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.1),
    layers.BatchNormalization(),
    layers.Dense(2) #binary classifiacation problem hence only 2 neurons in output layer
    
])
optimizer = tf.keras.optimizers.RMSprop(0.01)
dnnModel.compile(optimizer=optimizer,loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits= True),metrics = ['accuracy'])

In [8]:
dnnModel.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 15)                150       
_________________________________________________________________
dropout (Dropout)            (None, 15)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 19)                304       
_________________________________________________________________
batch_normalization (BatchNo (None, 19)                76        
_________________________________________________________________
dropout_1 (Dropout)          (None, 19)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 120)               2400      
_________________________________________________________________
batch_normalization_1 (Batch (None, 120)               4

In [9]:
dnnModel.fit(X_train_normalized , y_train, epochs =100)

Epoch 1/100
23/23 [==============================] - 0s 3ms/step - loss: 0.7561 - accuracy: 0.6390
Epoch 2/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5527 - accuracy: 0.7317
Epoch 3/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5287 - accuracy: 0.7584
Epoch 4/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5430 - accuracy: 0.7584
Epoch 5/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5105 - accuracy: 0.7725
Epoch 6/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4621 - accuracy: 0.8062: 0s - loss: 0.4646 - accuracy: 0.80
Epoch 7/100
23/23 [==============================] - 0s 3ms/step - loss: 0.4860 - accuracy: 0.7992
Epoch 8/100
23/23 [==============================] - 0s 3ms/step - loss: 0.4958 - accuracy: 0.7949
Epoch 9/100
23/23 [==============================] - 0s 3ms/step - loss: 0.4929 - accuracy: 0.7781
Epoch 10/100
23/23 [==============================] - 0s 2ms/step - loss:

23/23 [==============================] - 0s 2ms/step - loss: 0.4201 - accuracy: 0.8301
Epoch 83/100
23/23 [==============================] - 0s 3ms/step - loss: 0.4295 - accuracy: 0.8216
Epoch 84/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4251 - accuracy: 0.8216
Epoch 85/100
23/23 [==============================] - 0s 3ms/step - loss: 0.4171 - accuracy: 0.8371
Epoch 86/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4264 - accuracy: 0.8287
Epoch 87/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4441 - accuracy: 0.8188
Epoch 88/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4349 - accuracy: 0.8090
Epoch 89/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4454 - accuracy: 0.8034
Epoch 90/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4173 - accuracy: 0.8329
Epoch 91/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4320 - accuracy: 0.8258
Epoch 92/100


In [10]:
#checking test accuracy
test_loss,test_acc = dnnModel.evaluate(X_test_normalized , y_test, verbose=2)
print('\nTest accuracy :', test_acc)

6/6 - 0s - loss: 0.4232 - accuracy: 0.8324

Test accuracy : 0.832402229309082


In [39]:
y_pred = dnnModel.predict_classes(X_test)

In [67]:

idx = np.random.randint(1,len(y_test))
print('Index = ',idx,' Predicted :: ',y_pred[idx],'actual : ',y_test[idx])

Index =  27  Predicted ::  0 actual :  1


In [15]:
titanic.head()


Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0         0       3    1  22.0      1      0   7.2500           0           0   
1         1       1    0  38.0      1      0  71.2833           1           0   
2         1       3    0  26.0      0      0   7.9250           0           0   
3         1       1    0  35.0      1      0  53.1000           0           0   
4         0       3    1  35.0      0      0   8.0500           0           0   

   Embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1

In [61]:
#my survival
my_survival = [[1,1,20,1,1,71.0042,0,0,1]]

my_survival_scaled = sc.fit_transform(my_survival)

[[ 3.  1. 28. ...  1.  0.  0.]
 [ 3.  1. 28. ...  0.  0.  1.]
 [ 3.  1.  7. ...  0.  1.  0.]
 ...
 [ 1.  0. 31. ...  1.  0.  0.]
 [ 3.  1. 23. ...  0.  0.  1.]
 [ 3.  1. 19. ...  0.  0.  1.]]


In [62]:
z_pred = dnnModel.predict_classes(my_survival)
print(z_pred)

if z_pred == 0:
    print(' u ded lol')
else:
    print('well u gonna die other day')

[0]
 u ded lol
